//Created or Uptaded by Roxane Seibel / student number : 74527
//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré à partir d'un modèle.
//
//     Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
//     Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FinalTest.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel;
    using System.ComponentModel.DataAnnotations;

    public partial class User
    {
        public int Id { get; set; }
        [Required(ErrorMessage = "This Field is Required")]
        public string AccountNumber { get; set; }
        [Required(ErrorMessage = "This Field is Required")]
        public string Name { get; set; }
        [Required(ErrorMessage = "This Field is Required")]
        public string LastName { get; set; }
        [DisplayName("Balance Saving Account")]
        public int Balance { get; set; }
        public string Email { get; set; }
        [DisplayName("Password")]
        [Required(ErrorMessage = "This Field is Required")]
        public string Passeword { get; set; }
        [DisplayName("Balance Current Account")]
        public int AccountType { get; set; }
        public string LoginErrorMessage { get; set; }
    }
}
